### PR TITLE
Reworked structure and improved features

### PR DESCRIPTION
**Pull request by rpconroy**
Some changes include
- Configuration scheme
- additional command line arguments
- simplified actions (removed certain key requirements)
- logging from file or command line
- Allowed for json input stream
- fixed unit tests
etc.

### CODE REVIEW

**Comment by tcram** [comment]
I think it should be the responsibility of each user to configure logging in their own cli or entry point script to fit their use case.  This is why __init__.py has a default Null logging handler ... if a user doesn't want to set up logging, the Null handler will accommodate that.

I recommend all functions related to logging configuration in config.py be moved into the cli script.  We can go ahead and proceed with this pull request, and I can make this change in a separate branch afterwards.

**Comment by rpconroy** [comment]
Hi Tom, I've moved all the logging code to cli.py.

Before I moved the code, logging was only configured in cli.py and the default handler was still null if nothing was initialized. Basically, I added logging to config.py in case someone wanted an easy access point to initialize logging, either by config file or programmatically. Or, if we wanted a way to specify a logging config file as a command line argument.

**Comment by tcram** [comment]
Ok, thanks for doing that.  

Are we ready to merge this pull request?  I will rebuild the package and upload to PyPI once it's merged.  But one thing we should decide on before I do this is the current version number, which needs to be specified in `setup.py` and `__init__.py.`  I don't know much about software versioning and how it applies here ... do we increment this to version 0.2.1 or is this a major release (1.0.0)?

**Comment by rpconroy** [comment]
I think we're pretty much ready. I just added a 'mv' command, so I think it's good on features.

As for versioning, I think we'll have to make it a major release since much of the functionality is not backwards compatible. 

Also, what are your thoughts on adding a default `isd_s3_config` file to a users `~/.aws/` directory on installation? It's probably more than we need to do right now, but worth thinking about.

**Comment by tcram** [comment]
If we added a default config to `~/.aws/`, then I think we would need to support a command line `configure` option, similar to `aws configure` in the AWS CLI.  It could be called as `isd_s3 configure`, and would write to `~/.aws/isd_s3_config`.  Something to think about for future development.

**Pull request merged**
